sudo: required
dist: trusty

language: go

go:
  - 1.6

git:
    submodules: false

before_install:
  - pip install -U grpcio==1.0.1
#  - make dependencies

#before_script:
#  - make format
#  - make vet

script:
  - pip install grpcio
  - echo -e "import sys\nprint(sys.path)\nimport grpc" | python
#  - make test

#after_success:
#  - bash <(curl -s https://codecov.io/bash)