language: go

go:
  - 1.6

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get golang.org/x/tools/cmd/cover

script:
  - go fmt ./...
  - go vet ./...
  - go test -race ./...
  sh testCoverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)