# sudo: false
sudo: required
dist: trusty

language: go

go:
  - 1.6

git:
    submodules: false

#before_install:
#  - make dependencies

#before_script:
#  - make format
#  - make vet

script:
  - pip install grpcio
  - echo -e "import sys\nprint(sys.path)\nimport grpcio" | python
#  - make test

#after_success:
#  - bash <(curl -s https://codecov.io/bash)