language: go

sudo: false

go:
  - 1.6

#before_install:
#  - make dependencies

#before_script:
#  - make format
#  - make vet

script:
  - pip install grpcio --user
  - echo -e "import sys\nprint('\n'.join(sys.path))\nimport grpcio" | python
#  - make test

#after_success:
#  - bash <(curl -s https://codecov.io/bash)