language: go

# sudo: false

go:
  - 1.6

git:
    submodules: false

cache:
  directories:
  - $HOME/.local

#
addons:
  apt:
    packages:
    - gnulib

#before_install:
#  - make dependencies

#before_script:
#  - make format
#  - make vet

script:
  - ls -al .local || true
  - echo 1@@@@@@@@@@@@@@@@@@@@@@@@@
  - dpkg -l
  - echo 2@@@@@@@@@@@@@@@@@@@@@@@@@
#  - pip install grpcio --user
  - echo -e "import sys\nprint('\n'.join(sys.path))\nimport grpcio" | python
#  - make test

#after_success:
#  - bash <(curl -s https://codecov.io/bash)