language: go

sudo: false

go:
  - 1.6

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get golang.org/x/tools/cmd/cover

before_script:
  - go fmt ./...
  - go vet $(go list ./...)

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)